#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
name: test-suite
on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - 'pkg/doc/verifiable/**'
    - 'scripts/*_test_suite.sh'
    - '.github/workflows/test-suite.yml'
    - 'Makefile'
  pull_request:
    paths:
    - 'pkg/doc/verifiable/**'
    - 'scripts/*_test_suite.sh'
    - '.github/workflows/test-suite.yml'
    - 'Makefile'
jobs:
  vcTestSuite:
    name: VC test suite
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:

    - name: Setup Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Setup node
      uses: actions/setup-node@v3.4.1
      with:
        node-version: '16.x'

    - name: Setup mocha
      timeout-minutes: 10
      run: npm install -g mocha

    - uses: actions/checkout@v3

    - name: Run test suite
      timeout-minutes: 10
      run: make vc-test-suite

    - uses: actions/upload-artifact@v3
      with:
        name: vc-report
        path: build/vc-test-suite/suite/implementations/aries-framework-go-report.json
